package common;

import java.util.Scanner;
import java.util.function.Supplier;
import java.util.stream.Stream;

import org.eclipse.jdt.annotation.NonNull;

/**
 * Interface of (lazy) generators
 * 
 * @author Stéphane Lescuyer
 *
 * @param <T> the type of values generated by the generator
 */
public interface Generator<T> extends Supplier<T> {

	/**
	 * @return a user-friendly description of the generator
	 */
	public String name();
	
	/**
	 * @return the next generated value
	 */
	public T generate();
	
	@Override
	default public T get() {
		return generate();
	}
	
	/**
	 * @return a Java 8 {@link Stream} based on this generator
	 */
	default public Stream<T> toStream() {
		@SuppressWarnings("null")
		@NonNull Stream<T> res = Stream.generate(this);
		return res;
	}
	
	/**
	 * Presents the values generated by this generator
	 * on standard output
	 */
	default public void present() {
		System.out.println("Generator: " + name());
		System.out.println("<Hit Enter to keep generating, type a number to generate");
		System.out.println(" many samples at once, and type q[uit] to stop>");
		int i = 0;
		Scanner scanner = new Scanner(System.in);
		while (scanner.hasNextLine()) {
			String line = scanner.nextLine();
			if (line.equals("q") || line.equals("quit")) break;
			int nsamples = 1;
			if (!line.isEmpty()) {
				try (Scanner sc = new Scanner(line)) {
					if (!sc.hasNextInt()) continue;
					nsamples = sc.nextInt();
					if (sc.hasNext()) continue;
				}
			}
			for (int j = 0; j < nsamples; ++j) {
				T t = generate();
				System.out.println("[" + i++ + "] " + t.toString());
			}
		}
		scanner.close();
	}
	
}