---
name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: master  # Comment this line if you want to test the CI before opening a PR

jobs:
  gradle:
    runs-on: ubuntu-22.04
    timeout-minutes: 10  # Shorter than default timeout, to avoid burning minutes if something doesn't terminate

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
    
      - name: Execute Gradle build
        working-directory: Dolmen
        run: ./gradlew build
